version: '3.8'
services:
  # PostgreSQL (db) : 이미지 정보 저장할 데이터베이스
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: imagedb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  # Kafka & Zookeeper : 메세지 브로커 역할
  #                     이미지 UUID를 'embedding-service'로 전달
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - app_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app_net

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - app_net

  # image service : 이미지 업로드, 데이터베이스에 저장, Kafka에 UUID 저장
  image-service:
    build: ./image-service
    ports:
      - "5001:5000"
    environment:
      DATABASE_URI: postgresql://user:password@db:5432/imagedb
      KAFKA_BROKER: kafka:9092
    volumes:
      - image_data:/mnt/data/images  
    depends_on:
      - db
      - kafka
    networks:
      - app_net

  # embedding service : Kafka에서 UUID 소비, 해당 이미지 임베딩 해 weaviate에 저장
  embedding-service:
    build: ./embedding-service
    environment:
      KAFKA_BROKER: kafka:9092
      WEAVIATE_URL: http://weaviate:8080
    depends_on:
      - kafka
      - weaviate
    volumes:
      - image_data:/mnt/data/images
    networks:
      - app_net

  # weaviate : 이미지 임베딩을 저장하고 관리
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: '100'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './data'
      DEFAULT_VECTORIZER_MODULE: 'none'
    volumes:
      - ./data:/var/lib/weaviate
    networks:
      - app_net

volumes:
  db_data:
  image_data:

networks:
  app_net:
    driver: bridge
